// Bundles frontend/src/{player,playlists,splitter}/index entry points into
// ../static/{player,playlists,splitter}.js — the exact filenames the Rust
// binary embeds via include_str! (see concert-tracker/src/web/handlers.rs)
// and serves from disk in dev mode (see static_js_router in web/mod.rs).
//
// Each output is a standalone IIFE bundle (no shared chunk between entries —
// esbuild's IIFE format can't share code across outputs). Cross-module
// communication at runtime stays on window.Player/Playlists/Splitter/htmx,
// exactly as in the original hand-written JS; shared TypeScript code (the API
// client, generated types, DOM helpers) is duplicated into each bundle by
// design, not imported across entry points.
//
// All three bundles are Foldkit (Effect-TS) widgets — built minified on the
// es2022 target. The player is the final conversion (see
// docs/change/2026-06-25-foldkit-player.md); `just ts-verify` is retired now
// that every bundle is too large to review as unminified plain text. They're
// still committed artifacts so `cargo build` stays Node-free.
import * as esbuild from "esbuild";
import { fileURLToPath } from "node:url";
import path from "node:path";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const watch = process.argv.includes("--watch");

const banner = {
  js: "// @generated by concert-tracker/frontend/build.mjs from frontend/src — do not edit directly.",
};

const sharedOptions = {
  outdir: path.join(__dirname, "../static"),
  outExtension: { ".js": ".js" },
  bundle: true,
  format: "iife",
  platform: "browser",
  entryNames: "[name]",
  sourcemap: false,
  banner,
  logLevel: "info",
};

const foldkitOptions = {
  ...sharedOptions,
  entryPoints: {
    player: path.join(__dirname, "src/player/index.ts"),
    splitter: path.join(__dirname, "src/splitter/index.ts"),
    playlists: path.join(__dirname, "src/playlists/index.ts"),
  },
  target: "es2022",
  minify: true,
};

if (watch) {
  const ctx = await esbuild.context(foldkitOptions);
  await ctx.watch();
  console.log("esbuild: watching frontend/src for changes...");
} else {
  await esbuild.build(foldkitOptions);
}
