// Bundles frontend/src/{player,playlists,splitter}/index entry points into
// ../static/{player,playlists,splitter}.js — the exact filenames the Rust
// binary embeds via include_str! (see concert-tracker/src/web/handlers.rs)
// and serves from disk in dev mode (see static_js_router in web/mod.rs).
//
// Each output is a standalone IIFE bundle (no shared chunk between entries —
// esbuild's IIFE format can't share code across outputs). Cross-module
// communication at runtime stays on window.Player/Playlists/Splitter/htmx,
// exactly as in the original hand-written JS; shared TypeScript code (the API
// client, generated types, DOM helpers) is duplicated into each bundle by
// design, not imported across entry points.
//
// player.js and playlists.js are unminified with no sourcemap so the
// committed .js stays reviewable and reproducible (see `just ts-verify`,
// which fails CI if a rebuild produces a diff against the committed
// artifacts). splitter.js is a Foldkit (Effect-TS) bundle — built minified,
// on a newer target, and deliberately excluded from the `ts-verify` diff
// guard (the bundled Effect-TS runtime is too large to review as plain text;
// see docs/change/2026-06-19-foldkit-eval.md). It's still committed, so
// `cargo build` stays Node-free either way.
import * as esbuild from "esbuild";
import { fileURLToPath } from "node:url";
import path from "node:path";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const watch = process.argv.includes("--watch");

const banner = {
  js: "// @generated by concert-tracker/frontend/build.mjs from frontend/src — do not edit directly.",
};

const sharedOptions = {
  outdir: path.join(__dirname, "../static"),
  outExtension: { ".js": ".js" },
  bundle: true,
  format: "iife",
  platform: "browser",
  entryNames: "[name]",
  sourcemap: false,
  banner,
  logLevel: "info",
};

const reviewableOptions = {
  ...sharedOptions,
  entryPoints: {
    player: path.join(__dirname, "src/player.ts"),
    playlists: path.join(__dirname, "src/playlists.ts"),
  },
  target: "es2020",
  minify: false,
};

// Effect-TS requires a newer target than the other two bundles; minified
// because the bundled runtime is too large to keep reviewable unminified.
const foldkitOptions = {
  ...sharedOptions,
  entryPoints: {
    splitter: path.join(__dirname, "src/splitter/index.ts"),
  },
  target: "es2022",
  minify: true,
};

if (watch) {
  const [reviewableCtx, foldkitCtx] = await Promise.all([
    esbuild.context(reviewableOptions),
    esbuild.context(foldkitOptions),
  ]);
  await Promise.all([reviewableCtx.watch(), foldkitCtx.watch()]);
  console.log("esbuild: watching frontend/src for changes...");
} else {
  await Promise.all([esbuild.build(reviewableOptions), esbuild.build(foldkitOptions)]);
}
