// Bundles frontend/src/{player,playlists,splitter}/index entry points into
// ../static/{player,playlists,splitter}.js — the exact filenames the Rust
// binary embeds via include_str! (see concert-tracker/src/web/handlers.rs)
// and serves from disk in dev mode (see static_js_router in web/mod.rs).
//
// Each output is a standalone IIFE bundle (no shared chunk between entries —
// esbuild's IIFE format can't share code across outputs). Cross-module
// communication at runtime stays on window.Player/Playlists/Splitter/htmx,
// exactly as in the original hand-written JS; shared TypeScript code (the API
// client, generated types, DOM helpers) is duplicated into each bundle by
// design, not imported across entry points.
//
// Output is unminified with no sourcemap so the committed .js stays
// reviewable and reproducible (see `just ts-verify`, which fails CI if a
// rebuild produces a diff against the committed artifacts).
import * as esbuild from "esbuild";
import { fileURLToPath } from "node:url";
import path from "node:path";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const watch = process.argv.includes("--watch");

const banner = {
  js: "// @generated by concert-tracker/frontend/build.mjs from frontend/src — do not edit directly.",
};

const entryPoints = {
  player: path.join(__dirname, "src/player.ts"),
  playlists: path.join(__dirname, "src/playlists.ts"),
  splitter: path.join(__dirname, "src/splitter/index.ts"),
};

const options = {
  entryPoints,
  outdir: path.join(__dirname, "../static"),
  outExtension: { ".js": ".js" },
  bundle: true,
  format: "iife",
  target: "es2020",
  platform: "browser",
  entryNames: "[name]",
  minify: false,
  sourcemap: false,
  banner,
  logLevel: "info",
};

if (watch) {
  const ctx = await esbuild.context(options);
  await ctx.watch();
  console.log("esbuild: watching frontend/src for changes...");
} else {
  await esbuild.build(options);
}
